GET https://api.hubapi.com/crm/v3/objects/companies?hapikey=dea715b2-2096-4374-92e0-76e1eb65388e&properties=name_ar,name,description,domain,about_us,phone,linkedin_company_page,website
Content-Type: application/json
