GET https://api.hubapi.com/crm/v3/objects/companies?hapikey=f71c5668-eabb-4c8a-a2f5-5133f1570fdc&properties=name_ar,name,description,domain,about_us,phone,linkedin_company_page,website
Content-Type: application/json
