// https://developers.hubspot.com/docs/api/crm/properties

// Get ticket properties
GET https://api.hubapi.com/crm/v3/properties/company?archived=false&hapikey=dea715b2-2096-4374-92e0-76e1eb65388e

{
  "properties":"description,about_us,phone,linkedin_company_page"
}